---
title: "Isc_fig9"
author: "Carson Stacy"
date: "6/1/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This relates to the Cuevas metric.. I first need to translate their script into R.
growth_curves.py

Script that generates sample growth curves using the Zwietering growth curve logistic model.
Author: Daniel A. Cuevas (dcuevas08.at.gmail.com)
Date:   January 22, 2018
I plan to do this with an R script that I can source to here, but we will see what i do.

```{r}
library(reticulate)
library(tidyverse)
library(hexbin)
library(Rfast)

conda_list()[[1]][4] %>% 
  use_condaenv(required = TRUE)

# py_install("pandas")
# py_install("numpy")
# py_config()
# use_python("C:/Users/makov/AppData/Local/r-miniconda/envs/r-reticulate")
```

here is the script:
```{python}
# Import necessary libraries
import numpy as np
import pandas as pd


# Define the Zwietering logistic growth model
def logistic(time, y0, lag, mu, A):
    denom = (1 + np.exp(((4 * mu / A) * (lag - time)) + 2))
    return y0 + ((A - y0) / denom)


N = 1000  # Number of curves
t = 50  # Number of hours
np.random.seed(9)  # Set random number seed

# Generate growth curve parameters for all growth curves
# Starting OD = [0.05, 0.10]
y0 = abs(np.random.normal(0.05, 0.01, N))

# Biomass yield = [0.1, 1.2]
A = abs(np.random.normal(1, 0.5, N))


# Maximum growth rate = [A/t, 1.1A]
mu = [abs(np.random.normal(((a / t) + (np.random.normal(0.5,0.2,1) * 0.4))/2, 0.08, 1))[0] for a in A]

# Lag time = [0.0, 20.0]
lag = abs(np.random.normal(5, 10, N))

# Generate sample IDs for each growth curve
sample = ["sample{}".format(x) for x in range(N)]

# Generate the time vector of 30 minute intervals
time = np.arange(start=0, stop=t, step=0.5)

# Create a pandas DataFrame containing all parameter data
pheno = pd.DataFrame({"sample": sample, "y0": y0, "A": A, "mu": mu,
                      "lag": lag})


# Use parameters to generate growth curves
# Curves will be stored in a long format pandas DataFrame
curve_data = {"sample": [], "time": [], "od": []}
for idx, x in pheno.iterrows():
    sample = x["sample"]
    y0 = x["y0"]
    lag = x["lag"]
    mu = x["mu"]
    A = x["A"]
    log_curve = logistic(time, y0, lag, mu, A)
    for i, t in enumerate(time):
        curve_data["sample"].append(sample)
        curve_data["time"].append(t)
        curve_data["od"].append(log_curve[i])
curves = pd.DataFrame(curve_data)


```


```{r}


if (file.exists("curvesnormal9.Rda")) {
  load("curvesnormal9.Rda")
} else {
  curves <- as.data.frame(py$curves)
  save(curves,file="curvesnormal9.Rda")
}



library(tidyverse)
library(DescTools)


# curves %>%
#   group_by(sample) %>%
#   length(as.vector(curves$od))

library(MESS)

findmax <- curves %>%
    group_by(sample) %>%
    summarize(AUC = auc(time, od)) %>%
    arrange(desc(AUC)) %>%
    head(1)
findmax$sample
#sample 973 has highest AUC

library(reshape2)
#now let us change formatting to use pre-existing code I made.
curves_new <- dcast(curves,time~sample,value.var="od")



#to test, i want to take max value at each time point to make a control curve..
# I do this using the rowMaxs function from the Rfast package
# first i had to make it a numeric matrix, and then dropped time column
MakeMax <- rowMaxs((data.matrix(curves_new[-1])), value = TRUE)
curves_new$MakeMax <- MakeMax

curves_new <- curves_new[, c(1, ncol(curves_new),2:(ncol(curves_new)-1))]



colnames(curves_new)[-1] <- str_pad(colnames(curves_new)[-1], 10, pad = "0", side = "left" )

findmax$sample <- str_pad(findmax$sample, 10, pad = "0", side = "left")
# colnames(curves_new)
#glimpse(curves_new)


# View(curves_new)

```



```{r}
library(grofit)
library(DescTools)
library(openxlsx)
library(tidyverse)

#time at which to stop integration for AUC
t_stationary <- 24

if (file.exists("FinalOutPutfig9normal.Rda")) {
  load("FinalOutPutfig9normal.Rda")
} else {



#IMPORT DATA HERE AS DATA.FRAME
dat <- curves_new


#note: should always be 1 (first column)
timeColumn <- 1
#can be adjsuted. average of ctl replicates is recommended based on zero science (seems like a good start).
# controlColumn <- match(findmax$sample,names(dat))
controlColumn <- match("000MakeMax",names(dat))
#shouldn't change unless time column != 1
a <- 2
#ADJUST ME: total number of curves in table + 1
b <- ncol(dat)


firstRun <- TRUE
c <- 2
d <- length(dat[[timeColumn]])
#d <- 20 #this is where 'stationary phase' would traditionally be considered fully reached
for (j in c:d) {


fit9 <- gcFitSpline(dat[[timeColumn]], dat[[controlColumn]], gcID = "spline",
            control = grofit.control())
lambda <- as.numeric(fit9$parameters$lambda)
mumax <- as.numeric(fit9$parameters$mu)
K <- as.numeric(fit9$parameters$A)
upperbound <- as.numeric(dat[j,1])
#upperbound <- dat[timeColumn[[j]]
#AUCraw <- AUC(dat[1:length(dat[[timeColumn]]),1], dat[1:length(dat[[controlColumn]]),controlColumn])
AUCraw <- AUC(dat[1:j,1], dat[1:j,controlColumn])
PI <- 0
Isc9 <- 0

storage.vector_fig9 <- data.frame( "mumax"= mumax, "K"= K, "lambda"= lambda, "UpperBound" = upperbound, "AUC" = AUCraw, "PI" = PI, "Isc" = Isc9, stringsAsFactors=FALSE)


for (i in a:b) {
if(i != controlColumn) {
fit9 <- gcFitSpline(dat$time, dat[[i]], gcID = "spline444",
            control = grofit.control())
#plot(fit9)

lambda <- as.numeric(fit9$parameters$lambda)
mumax <- as.numeric(fit9$parameters$mu)
K <- as.numeric(fit9$parameters$A)
upperbound <- as.numeric(dat[j,1])

  AUCraw <- AUC(dat[1:j,1], dat[1:j,i])
  if(i ==2) {
    PI <- 0
  } else {
    PI <- (1 - (AUCraw/storage.vector_fig9$AUC[1])) * 100
  }

  Isc9 <-  (1 - sqrt((AUCraw*K)/(storage.vector_fig9$AUC[1]*storage.vector_fig9$K[1]))) * 100


storage.vector_fig9 <- rbind(storage.vector_fig9, c( mumax, K, lambda, upperbound, as.numeric(AUCraw), PI, as.numeric(Isc9)))


}
}
#output <- rbind
if(firstRun == TRUE) {
  #something
  firstRun <- FALSE
  rownames(storage.vector_fig9) <- colnames(dat[-timeColumn])
  FinalOutPutfig9 <- storage.vector_fig9
} else {
  rownames(storage.vector_fig9) <- colnames(dat[-timeColumn])
  FinalOutPutfig9 <- rbind(FinalOutPutfig9, storage.vector_fig9)
}

}
#storage.vector_fig9 <- storage.vector_fig9[-c(1), ]

#storage.vector_fig9
#Below code to get rid of scientific notation:
options(scipen=999)
#here is how to get back to scientific notation: options(scipen=0)



library(data.table)
setDT(FinalOutPutfig9, keep.rownames = TRUE)
#here I'm fixing the group names to not say replicates
# FinalOutPutfig9$rn <- c(str_replace_all(string=FinalOutPutfig9$rn,pattern="\\l.*$",replacement="l"))
FinalOutPutfig9$rn <- substr(FinalOutPutfig9$rn, 1, 10)
# df$col1 <- strtrim(df$col, 1, 1)

  save(FinalOutPutfig9,file="FinalOutPutfig9normal.Rda")
}

# for writing a data.frame or list of data.frames to an xlsx file
#write.xlsx(FinalOutPutfig9, 'Isc_fig9ISC.xlsx')
#FinalOutPUtfig9save <- FinalOutPutfig9

FinalOutPutfig9 %>%
  arrange((Isc))
```



```{r}
library(MESS)
gdIsc <- FinalOutPutfig9 %>%
        group_by(rn, UpperBound) %>%
        #group_by(UpperBound) %>%
        summarise(Isc = mean(Isc))
gdVr <- gdIsc %>%
  group_by(rn) %>%
  summarize(Vr = auc(UpperBound, Isc)/(max(UpperBound) - min(UpperBound)))

gdPI <- FinalOutPutfig9 %>%
        group_by(rn) %>%
        summarise(PI = mean(PI))



ggFinalOutPutfig9_PI <- FinalOutPutfig9 %>%
  group_by(rn) %>%
  select(-c(mumax,K,lambda)) %>%
  ggplot(aes(x=UpperBound, y=PI, color = rn)) +
  geom_point() +
  geom_smooth() +
  geom_hline(data = gdPI, yintercept = gdPI$PI) +
  theme(legend.position = "none")
# ggFinalOutPutfig9_PI

ggFinalOutPutfig9_filtIsc <- FinalOutPutfig9 %>%
  group_by(rn) %>%
  select(-c(mumax,K,lambda)) %>%
  ggplot(aes(x=UpperBound, y=Isc, color = rn)) +
    geom_point() +
    geom_smooth() +
    geom_hline(data = gdIsc, yintercept = gdVr$Vr) +
    theme(legend.position = "none")
# ggFinalOutPutfig9_filtIsc


#here is more work to allow for a new 'max' to be control
MakeMax_pandas <- data.frame(
  rep("Max", 100),
  seq(0, 49.5, by = 0.5),
  MakeMax
)
colnames(MakeMax_pandas) <- c("sample", "time", "od")

curves <- rbind(curves, MakeMax_pandas)


AUCfig9 <- curves %>%
    group_by(sample) %>%
    summarize(AUC = auc(time,od)) %>%
    mutate(rAUC = 100*(1-AUC/max(AUC)))



py_A <- c(py$pheno$A, max(py$pheno$A))
py_pheno_A <- c(py_A[1],py_A[length(py_A)],py_A[-c(1,length(py_A))])

py_mu <- c(py$pheno$mu, max(py$pheno$mu))
py_pheno_mu <- c(py_mu[1],py_mu[length(py_mu)],py_mu[-c(1,length(py_mu))])

py_y0 <- c(py$pheno$y0, max(py$pheno$y0))
py_pheno_y0 <- c(py_y0[1],py_y0[length(py_y0)],py_y0[-c(1,length(py_y0))])



rel_mu <- (py_pheno_mu/max(py_pheno_mu))

rel_A <- (py_pheno_A/max(py_pheno_A))

gdVr

gd <- cbind(gdVr, gdPI, AUCfig9)
gd <- gd[-c(3,5)]


ggplot( data =py$curves[,1:3], aes(x = time, y=od, group = sample, colour = sample)) +
  geom_line(size = 0.09, alpha = 0.9, aes(colour = sample)) +
  theme(legend.position = "none")

# ggsave("Cuevas_all_curves_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes(x = gd$PI, y = gd$Vr)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_binhex() +
  geom_abline() +
  theme_classic()

# ggsave("Cuevas_PIvsVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


qqplot(gdPI$PI,gdVr$Vr)
# ggsave("Cuevas_PIvsVrqqplot_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


ggplot(data = NULL, aes(x = AUCfig9$rAUC, y = gdPI$PI, color = rel_mu)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(6))
# ggsave("Cuevas_rAUCvsPI_colrelmu_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")



ggplot(data = NULL, aes(x = AUCfig9$rAUC, y = gdVr$Vr, color = rel_mu)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(6))
# ggsave("Cuevas_rAUCvsVr_colrelmu_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


ggplot(data = NULL, aes(x = py_pheno_mu, y = gdVr$Vr, colour = gd$PI)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(6))
# ggsave("Cuevas_muvsVr_colPI_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


ggplot(data = NULL, aes(x = py_pheno_mu, y = gdPI$PI, colour = gd$Vr)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(20))
# ggsave("Cuevas_muvsPI_colVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


ggplot(data = NULL, aes(x = py_pheno_mu, y = AUCfig9$AUC, colour = gd$Vr)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(20))
# ggsave("Cuevas_muvsAUC_colVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


ggplot(data = NULL, aes(x = py_pheno_A , y = gdVr$Vr, colour = gd$PI)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(20))
# ggsave("Cuevas_AvsVr_colPI_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


ggplot(data = NULL, aes(x = py_pheno_A , y = gdPI$PI, colour = gd$Vr)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(20))
# ggsave("Cuevas_AvsPI_colVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


ggplot(data = NULL, aes(x = py_pheno_y0 , y = gdPI$PI, colour = gd$Vr)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(20))
# ggsave("Cuevas_y0vsPI_colVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


ggplot(data = NULL, aes(x = py_pheno_mu , y = py_pheno_A, colour = gd$Vr)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(6))
# ggsave("Cuevas_muvsA_colVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes(x = py_pheno_mu , y = py_pheno_A, colour = gd$PI)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(6))
# ggsave("Cuevas_muvsA_colPI_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes(x = py_pheno_mu , y = py_pheno_A, colour = gd$rAUC)) +
  geom_point(alpha = 0.8) +
  geom_smooth(method = "lm") +
  scale_color_gradientn(colours = rainbow(6))
# ggsave("Cuevas_muvsA_colrAUC_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

# now with relative parameters
ggplot(data = NULL, aes(x = rel_mu, y = gdVr$Vr)) +
  geom_point() +
  geom_smooth(method = "lm")
# ggsave("Cuevas_relmuvsVr_colnone_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes(x = rel_mu, y = gdPI$PI)) +
  geom_point() +
  geom_smooth(method = "lm")
# ggsave("Cuevas_relmuvsPI_colnone_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes(x = rel_mu, y = AUCfig9$AUC)) +
  geom_point() +
  geom_smooth(method = "lm")
# ggsave("Cuevas_relmuvsAUC_colnone_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes(x = rel_A , y = gdVr$Vr)) +
  geom_point() +
  geom_smooth(method = "lm")
# ggsave("Cuevas_relAvsVr_colnone_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes(x = rel_A , y = gdPI$PI)) +
  geom_point() +
  geom_smooth(method = "lm")
# ggsave("Cuevas_relAvsPI_colnone_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


ggplot(data = NULL, aes( x = (py_pheno_A - py_pheno_y0) + (0.25*py_pheno_mu), y = gdVr$Vr, color = gdPI$PI)) +
  geom_point()
# ggsave("Cuevas_GSvsVr_colPI_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes( x = (py_pheno_A - py_pheno_y0) + (0.25*py_pheno_mu), y = gdVr$Vr, color = AUCfig9$rAUC)) +
  geom_point()
# ggsave("Cuevas_GSvsVr_colrAUC_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes( x = (py_pheno_A - py_pheno_y0) + (0.25*py_pheno_mu), y = gdVr$Vr, color = py_pheno_mu)) +
  geom_point()
# ggsave("Cuevas_GSvsVr_colmu_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes( x = (py_pheno_A - py_pheno_y0) + (0.25*py_pheno_mu), y = gdVr$Vr, color = py_pheno_A)) +
  geom_point()
# ggsave("Cuevas_GSvsVr_colA_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

ggplot(data = NULL, aes( x = (py_pheno_A) + (0.25*py_pheno_mu), y = gdVr$Vr, color = py_pheno_A)) +
  geom_point()
# ggsave("Cuevas_GSvsVr_colA_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

#compare GS with PI
ggplot(data = NULL, aes( x = (py_pheno_A - py_pheno_y0) + (0.25*py_pheno_mu), y = gdPI$PI, color = py_pheno_A)) +
  geom_point()
# ggsave("Cuevas_GSvsPI_colA_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

#compare GS with A
ggplot(data = NULL, aes( x = (py_pheno_A - py_pheno_y0) + (0.25*py_pheno_mu), y = py_pheno_A, color =gdVr$Vr )) +
  geom_point()
# ggsave("Cuevas_GSvsA_colVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

#compare GS with PI
ggplot(data = NULL, aes( x = (py_pheno_A - py_pheno_y0) + (0.25*py_pheno_mu), y = gdPI$PI, color = gdVr$Vr)) +
  geom_point()
# ggsave("Cuevas_GSvsPI_colVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")



#compare GS with A-y0
ggplot(data = NULL, aes( x = (py_pheno_A - py_pheno_y0) + (0.25*py_pheno_mu), y = py_pheno_A - py_pheno_y0, color =gdVr$Vr )) +
  geom_point()
# ggsave("Cuevas_GSvsAy0_colVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")

# compare GS with mu
ggplot(data = NULL, aes( x = (py_pheno_A - py_pheno_y0) + (0.25*py_pheno_mu), y = py_pheno_mu, color =gdVr$Vr )) +
  geom_point()
# ggsave("Cuevas_GSvsmu_colVr_normaldistrocode10k.tiff", path = "Visualizations", units = "in", width = 8, height = 6, dpi=300, compression = "lzw")


```