---
title: "ZhangSulfData"
author: "Carson Stacy"
date: "7/20/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(DescTools)
library(MESS)
#this should normally be commented out, except when knitting. it is where I downloaded grofit b/c it is depreicated now...
# install.packages("~/Downloads/grofit_1.1.1-1.tar.gz", repos = NULL, type = "source")
library(grofit)
library(readxl)
library(ggpubr)
library(here)
options(scipen = 999)

```

```{r}

#IMPORT DATA HERE AS DATA.FRAME

# dat <- read_csv("~/Downloads/Supplemental_Table_S1_ready.csv")

dat <- read_excel(here("/Data/Raw/Zhang/ZhangGC.xls"))


trim <- 15

colnames(dat)[1] <- "time"

colnames(dat)[-1] <- str_pad(colnames(dat)[-1], trim, pad = "0", side = "left" )
```

```{r}

timeColumn <- 1
#can be adjsuted. average of ctl replicates is recommended based on zero science (seems like a good start).
controlColumn <- 2
#shouldn't change unless time column != 1
a <- 2
#ADJUST ME: total number of curves in table + 1
b <- as.numeric(ncol(dat))
#What is the timepoint at which stationary phase is reached?
t_stationary <- 94
# t_stationary <- 58
# t_stationary <- 22

firstRun <- TRUE
c <- 2
d <- as.numeric(length(dat[[timeColumn]]))
#d <- 20 #this is where 'stationary phase' would traditionally be considered fully reached
for (j in c:d) {


figZ <- gcFitSpline(dat[[timeColumn]], dat[[controlColumn]], gcID = "spline",
            control = grofit.control())
lambda <- as.numeric(figZ$parameters$lambda)
mumax <- as.numeric(figZ$parameters$mu)
K <- as.numeric(figZ$parameters$A)
upperbound <- as.numeric(dat[j,1])
#upperbound <- dat[timeColumn[[j]]
#AUCraw <- AUC(dat[1:length(dat[[timeColumn]]),1], dat[1:length(dat[[controlColumn]]),controlColumn])
AUCraw <- AUC(deframe(dat[1:j,1]), deframe(dat[1:j,controlColumn]))
PI <- 0
IscZ <- 0

storage.vector_figZ <- data.frame( "mumax"= mumax, "K"= K, "lambda"= lambda, "UpperBound" = upperbound, "AUC" = AUCraw, "PI" = PI, "Isc" = IscZ, stringsAsFactors=FALSE)


for (i in a:b) {
if(i != controlColumn) {
figZ <- gcFitSpline(dat$time, dat[[i]], gcID = "spline444",
            control = grofit.control())
#plot(figZ)

lambda <- as.numeric(figZ$parameters$lambda)
mumax <- as.numeric(figZ$parameters$mu)
K <- as.numeric(figZ$parameters$A)
upperbound <- as.numeric(dat[j,1])

  AUCraw <- AUC(deframe(dat[1:j,1]), deframe(dat[1:j,i]))
  if(i == controlColumn) {
    PI <- 0
  } else {
    PI <- (1 - (AUCraw/storage.vector_figZ$AUC[1])) * 100
  }

  IscZ <-  (1 - sqrt((AUCraw*K)/(storage.vector_figZ$AUC[1]*storage.vector_figZ$K[1]))) * 100


storage.vector_figZ <- rbind(storage.vector_figZ, c( mumax, K, lambda, upperbound, as.numeric(AUCraw), PI, as.numeric(IscZ)))


}
}
#output <- rbind
if(firstRun == TRUE) {
  #something
  firstRun <- FALSE
  rownames(storage.vector_figZ) <- colnames(dat[-timeColumn])
  FinalOutPutfigZhang <- storage.vector_figZ
} else {
  rownames(storage.vector_figZ) <- colnames(dat[-timeColumn])
  FinalOutPutfigZhang <- rbind(FinalOutPutfigZhang, storage.vector_figZ)
}

}
#storage.vector_figZ <- storage.vector_figZ[-c(1), ]

#storage.vector_figZ
#Below code to get rid of scientific notation:
options(scipen=999)
#here is how to get back to scientific notation: options(scipen=0)



library(data.table)
setDT(FinalOutPutfigZhang, keep.rownames = TRUE)
#here I'm fixing the group names to not say replicates
# FinalOutPutfigZhang$rn <- c(str_replace_all(string=FinalOutPutfigZhang$rn,pattern="\\l.*$",replacement="l"))
FinalOutPutfigZhang$rn <- substr(FinalOutPutfigZhang$rn, 1, trim)
# df$col1 <- strtrim(df$col, 1, 1)

IscOrderedOutputFigZ <- FinalOutPutfigZhang %>%
  arrange((Isc))



if (exists("maxIsc") == TRUE) {
  save(FinalOutPutfigZhang,file="FinalOutPutfigZhang.Rda")
} else {
maxIsc <- IscOrderedOutputFigZ[1,1]
}
# }

# for writing a data.frame or list of data.frames to an xlsx file
#write.xlsx(FinalOutPutfigZhang, 'Isc_figZISC.xlsx')
#FinalOutPutfigZhangsave <- FinalOutPutfigZhang

IscOrderedOutputFigZ







#we are only going to stationary phase for Vr calc with this formula:

gdIsc <- FinalOutPutfigZhang %>%
        group_by(rn, UpperBound) %>%
        filter(UpperBound <= t_stationary) %>%
        summarise(Isc = mean(Isc))
gdVr <- gdIsc %>%
  group_by(rn) %>%
  summarize(Vr = auc(UpperBound, Isc, type = "spline")/(max(UpperBound) - min(UpperBound)))

gdPI <- FinalOutPutfigZhang %>%
        group_by(rn) %>%
        summarise(PI = mean(PI))

AUCfigZ <- FinalOutPutfigZhang %>%
    filter(UpperBound == max(FinalOutPutfigZhang$UpperBound)) %>%
    mutate(rAUC = 100*(AUC/max(AUC))) %>%
    arrange(rn) %>%
    select(c(-1,-4, -5, -6, -7, -8))
AUCfigZ



trimAUCfigZ <- FinalOutPutfigZhang %>%
    filter(UpperBound == t_stationary) %>%
    mutate(AUCtrim = 100*(AUC/max(AUC))) %>%
    arrange(rn) %>%
    select("AUCtrim")


gd <- cbind(gdVr, gdPI, AUCfigZ, trimAUCfigZ)
gd <- gd[-3]
gd


gd$virus <- c("CTL", "SSV20", "SSV21", "SSV22")

gd$virus_factor <- factor(gd$virus, levels = c("CTL", "SSV20", "SSV21", "SSV22"))


gd$host <- c(
    rep("E5-1-F", 4)
)

gdZhang <- gd

ggplot(data = NULL, aes(x = gd$PI, y = gd$Vr)) +
  geom_point() +
  geom_smooth(method = "lm") +
  geom_abline() +
  theme_classic()


#now get change in Isc over time plot

# HPI <- FinalOutPutfigZhang$
# CTLIsc <- 
# SSV20Isc <- 
# SSV21Isc <- 
# SSV22Isc <- 

ggplot( data = FinalOutPutfigZhang, aes(x = UpperBound, y = Isc, color = as.factor(rn))) +
  geom_point() +
  geom_line()


ggplot( data = FinalOutPutfigZhang, aes(x = UpperBound, y = PI, color = as.factor(rn))) +
  geom_point() +
  geom_line()

ggplot( data = FinalOutPutfigZhang, aes(x = UpperBound, y = AUC, color = as.factor(rn))) +
  geom_point() +
  geom_line()
```



```{r}

ggplot(data = gd, aes(x = Vr, y = mumax, color = as.factor(virus))) +
  geom_point() +
  #geom_smooth(method = "lm") +
  #scale_color_gradientn(colours = rainbow(6)) +
  # facet_wrap(~host) +
  theme_bw()

ggplot(data = gd, aes(y = PI, x = Vr, color = as.factor(virus))) +
  geom_point() +
  #geom_smooth(method = "lm") +
  #scale_color_gradientn(colours = rainbow(6)) +
  # facet_wrap(~host) +
  theme_bw()

ggplot(data = gd, aes(y = mumax, x = PI, color = as.factor(virus))) +
  geom_point() +
  #geom_smooth(method = "lm") +
  #scale_color_gradientn(colours = rainbow(6)) +
  # facet_wrap(~host) +
  theme_bw()

ggplot(data = gd, aes(y = mumax, x = rAUC, color =  as.factor(virus))) +
  geom_point() +
  #geom_smooth(method = "lm") +
  #scale_color_gradientn(colours = rainbow(6)) +
  # facet_wrap(~host) +
  theme_bw() +
    scale_x_reverse()

ggplot(data = gd, aes(y = rAUC, x = Vr)) +#, color =  as.factor(virus))) +
  geom_point() +
  #geom_smooth(method = "lm") +
  #scale_color_gradientn(colours = rainbow(6)) +
  # facet_wrap(~host) +
   geom_smooth(method='lm') +
  theme_bw()

ggscatter(gd, x = "rAUC", y = "Vr", add = "reg.line") +
  stat_cor(label.y = 5, 
           aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")))


ggplot(data = gd, aes(y = K, x = Vr, color = as.factor(virus))) +
  geom_point() +
  #geom_smooth(method = "lm") +
  #scale_color_gradientn(colours = rainbow(6)) +
  # facet_wrap(~host) +
  theme_bw()

ggplot(data = gd, aes(y = K, x = PI, color = as.factor(virus))) +
  geom_point() +
  #geom_smooth(method = "lm") +
  #scale_color_gradientn(colours = rainbow(6)) +
  # facet_wrap(~host) +
  theme_bw()

ggplot(data = gd, aes(y = K, x = rAUC, color = as.factor(virus))) +
  geom_point() +
  #geom_smooth(method = "lm") +
  #scale_color_gradientn(colours = rainbow(6)) +
  # facet_wrap(~host) +
  theme_bw()

ggplot(data = gd, aes(x = K, y = mumax, color = as.factor(virus))) +
  geom_point() +
  #geom_smooth(method = "lm") +
  #scale_color_gradientn(colours = rainbow(6)) +
  # facet_wrap(~host) +
  theme_bw() +
    scale_x_reverse()
```


```{r fig.height=6, fig.width=8}
options(scipen = 0)
ggscatter(gd, x = "AUCtrim", y = "Vr", add = "reg.line") +
  stat_cor(label.y = 5, 
           aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")))

ggscatter(gd, x = "mumax", y = "Vr", add = "reg.line") +
  stat_cor(label.y = 5, 
           aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")))

ggscatter(gd, x = "K", y = "Vr", 
          add = "reg.line", 
          fill = "virus_factor", 
          shape = 21, size = 2, 
          # conf.int = TRUE, 
          palette = c("black", "orange", "red", "blue", "yellow", "beige", "light green")) +
  facet_wrap(~host) +
  stat_cor(label.y = 10, label.x = 1.2, 
           aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")))



options(scipen=999)
```

```{r}
ggplot(data=gd, aes(y = Vr, x = virus)) +
    geom_boxplot() +
    labs(fill="") +
    facet_wrap(~host, nrow = 1) +
    ylab(expression(V[R])) +
  theme_bw()

ggplot(data=gd, aes(y = K, x = virus)) +
    geom_boxplot() +
    labs(fill="") +
    facet_wrap(~host, nrow = 1) +
    scale_y_reverse() +
    ylab("Max Density (A)") +
  theme_bw()

```